// Optional offline reading copies. No Unreal/runtime dependency.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {Marked, Renderer} from './vendor/marked.mjs';

const learning = fileURLToPath(new URL('../', import.meta.url));
const project = path.dirname(learning);
const output = path.join(learning, 'html');
const marker = '<!-- Generated by learning/tools/build-html.mjs. Edit Markdown sources. -->';
const check = process.argv.includes('--check');
if (process.argv.slice(2).some(arg => arg !== '--check')) throw new Error('Usage: node learning/tools/build-html.mjs [--check]');
const walk = dir => fs.readdirSync(dir, {withFileTypes: true}).flatMap(entry => {
  const item = path.join(dir, entry.name);
  if (item === output || entry.name === 'vendor') return [];
  return entry.isDirectory() ? walk(item) : [item];
});
const slash = value => value.replaceAll('\\', '/');
const relative = file => slash(path.relative(learning, file));
const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const digest = value => createHash('sha256').update(value).digest('hex');
const read = file => fs.readFileSync(file, 'utf8');
const inside = file => { const rel = path.relative(project, file); return !rel.startsWith('..') && !path.isAbsolute(rel); };
const files = walk(learning).filter(file => file.endsWith('.md')).sort();
const pages = new Map(files.map(file => [file, path.join(output, relative(file).replace(/\.md$/, '.html'))]));
const expectedPages = new Set([...pages.values(), path.join(output, 'index.html')]);
const url = (from, to) => slash(path.relative(path.dirname(from), to)).split('/').map(encodeURIComponent).join('/');
const css = read(new URL('./html.css', import.meta.url));
const client = read(new URL('./html.js', import.meta.url));
const links = [];
const ids = new Map();
const generated = new Map();
const catalog = [];

function rewrite(href, source, destination) {
  if (/^(https?:|mailto:)/i.test(href)) return href;
  if (/^[a-z][a-z0-9+.-]*:/i.test(href) || href.startsWith('//')) throw new Error(`Unsupported URL: ${relative(source)} ${href}`);
  const match = /^([^?#]*)(\?[^#]*)?(#.*)?$/.exec(href);
  const target = match[1] ? path.resolve(path.dirname(source), decodeURIComponent(match[1])) : source;
  if (!inside(target) || (!fs.existsSync(target) && !expectedPages.has(target))) throw new Error(`Missing/outside link: ${relative(source)} ${href}`);
  const converted = pages.get(target) || target;
  const fragment = match[3] || '';
  links.push({from: relative(source), target: converted, fragment: decodeURIComponent(fragment.slice(1))});
  return url(destination, converted) + (match[2] || '') + fragment;
}

function shell(title, destination, body, toc = '', source = null) {
  const nav = [['전체 문서', 'index.html'], ['P0 시작', 'P0/README.html'], ['A 수업', 'P0/A/README.html'], ['B 수업', 'P0/B/README.html'], ['통합', 'P0/INTEGRATION.html']];
  return `${marker}
<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escape(title)} · A·B 학습 자료</title><style>${css}</style></head>
<body><a class="skip" href="#main">본문으로 이동</a>
<header class="site-header"><a class="brand" href="${url(destination, path.join(output, 'index.html'))}">A · B 개발 학습 자료</a>
<nav aria-label="주요 문서">${nav.map(([label, target]) => `<a href="${url(destination, path.join(output, target))}"${path.join(output, target) === destination ? ' aria-current="page"' : ''}>${label}</a>`).join('')}</nav></header>
<div class="layout${toc ? '' : ' wide'}">${toc ? `<aside><details open><summary>이 문서의 목차</summary><nav aria-label="문서 목차">${toc}</nav></details></aside>` : ''}
<main id="main">${source ? `<div class="document-meta"><span>${escape(relative(source))}</span><a href="${url(destination, source)}">Markdown 원본</a></div>` : ''}${body}
<footer>오프라인 HTML 읽기본 · 작성·검증 상태는 원문을 따릅니다.${source ? ' 원문을 수정한 뒤 HTML을 다시 생성해 주세요.' : ''}<button type="button" class="print-button">인쇄 / PDF</button></footer></main></div>
<script>${client}</script></body></html>
`;
}

for (const source of files) {
  const destination = pages.get(source);
  const markdown = read(source);
  const headings = [];
  const usedIds = new Set([...markdown.matchAll(/<a\s+id=["']([^"']+)["']/g)].map(match => match[1]));
  const parser = new Marked({gfm: true, breaks: false});
  const defaults = new Renderer();
  parser.use({renderer: {
    heading(token) {
      const content = this.parser.parseInline(token.tokens);
      const label = content.replace(/<[^>]+>/g, '');
      const base = token.text.toLowerCase().replace(/[^\p{L}\p{N}\s_-]/gu, '').trim().replace(/\s+/g, '-') || 'section';
      let id = base;
      for (let n = 2; usedIds.has(id); n++) id = `${base}-${n}`;
      usedIds.add(id);
      headings.push({id, label, depth: token.depth});
      return `<h${token.depth} id="${escape(id)}">${content}</h${token.depth}>\n`;
    },
    link(token) {
      const href = rewrite(token.href, source, destination);
      return `<a href="${escape(href)}"${token.title ? ` title="${escape(token.title)}"` : ''}>${this.parser.parseInline(token.tokens)}</a>`;
    },
    image(token) {
      return `<img src="${escape(rewrite(token.href, source, destination))}" alt="${escape(token.text)}" loading="lazy">`;
    },
    table(token) {
      return `<div class="table-scroll" role="region" aria-label="가로로 스크롤 가능한 표" tabindex="0">${defaults.table.call(this, token)}</div>`;
    },
    html({text}) {
      // Preserve explicit anchors/line breaks, but never execute document HTML.
      return /^(?:<a\s+id=["'][^"'<>]+["']\s*>(?:\s*<\/a>)?|<\/a>|<br\s*\/?>)\s*$/i.test(text) ? text : escape(text);
    },
  }});
  const body = parser.parse(markdown);
  const title = headings.find(heading => heading.depth === 1)?.label || path.basename(source, '.md');
  const toc = headings.filter(heading => heading.depth > 1 && heading.depth < 4)
    .map(heading => `<a class="level-${heading.depth}" href="#${escape(heading.id)}">${heading.label}</a>`).join('');
  ids.set(destination, usedIds);
  generated.set(destination, shell(title.replace(/&amp;/g, '&'), destination, body, toc, source));
  catalog.push({source: relative(source), output: relative(destination), title, sha256: digest(fs.readFileSync(source))});
}

const groups = [
  ['먼저 읽기', item => !item.source.includes('/') || item.source === 'P0/README.md' || item.source === 'P0/COMMON.md'],
  ['P0 · A 수업', item => /^P0\/A\/[^/]+\.md$/.test(item.source)],
  ['P0 · B 수업', item => /^P0\/B\/[^/]+\.md$/.test(item.source)],
  ['P0 · 통합', item => /^P0\/[^/]*INTEGRATION\.md$/.test(item.source)],
  ['재현·검수 증거', item => item.source.startsWith('P0/')],
  ['수업 양식·제공 도구', item => /^(templates|tools)\//.test(item.source)],
  ['P1 · 기존 계획', item => item.source.startsWith('P1/')],
  ['P2 · 기존 계획', item => item.source.startsWith('P2/')],
];
const index = path.join(output, 'index.html');
const remaining = new Set(catalog);
const sections = groups.map(([title, matches]) => {
  const items = [...remaining].filter(matches).sort((a, b) => Number(!a.source.endsWith('README.md')) - Number(!b.source.endsWith('README.md')) || a.source.localeCompare(b.source, 'ko', {numeric: true}));
  items.forEach(item => remaining.delete(item));
  return `<section class="catalog-group"><h2>${title}</h2><ul class="document-list">${items.map(item => `<li data-search="${escape(`${item.source} ${item.title}`.toLowerCase())}"><a href="${url(index, path.join(learning, item.output))}">${item.title}</a><small>${escape(item.source)}</small></li>`).join('')}</ul></section>`;
}).join('');
if (remaining.size) throw new Error('Add an index group for new documents.');
generated.set(index, shell('학습 문서 모음', index, `<p class="eyebrow">REFERENCE LEARNING LIBRARY</p><h1>작은 기능부터,<br>함께 완성하는 P0.</h1>
<p class="intro">A·B 학습 문서 ${catalog.length}개를 HTML로 모았습니다. P0 시작 문서에서 공통 계약을 읽고, 각 역할의 수업과 단계별 통합을 순서대로 진행하세요.</p>
<div class="notice">원문의 Verified·Draft·Planned와 SHA를 그대로 보존했습니다. HTML 변환은 수업이나 게임 검수의 추가 통과를 의미하지 않습니다. P1·P2는 기존 계획 문서입니다.</div>
<label class="search-label" for="document-search">문서 찾기</label><input id="document-search" type="search" placeholder="제목 또는 경로 검색 · 예: G2, 보드, Android" autocomplete="off">
<p id="search-count" role="status" aria-live="polite">${catalog.length}개 문서</p><div class="catalog">${sections}</div><p id="search-empty" hidden>일치하는 문서가 없습니다. 다른 검색어를 입력해 주세요.</p>
<p class="reference-note">학습 문서 링크는 HTML로 연결됩니다. 정식 명세·코드·JSON·화면 증거는 저장소의 원본으로 연결되므로 저장소 폴더 구조를 유지해 주세요.</p>`));

for (const link of links) {
  if (link.fragment && ids.has(link.target) && !ids.get(link.target).has(link.fragment)) {
    throw new Error(`Missing HTML anchor: ${link.from} -> ${link.target}#${link.fragment}`);
  }
}
generated.set(path.join(output, 'manifest.json'), JSON.stringify({generator: 'learning/tools/build-html.mjs', parser: 'marked 17.0.5 (MIT)', documents: catalog}, null, 2) + '\n');
for (const [file, content] of generated) {
  if (check) {
    if (!fs.existsSync(file) || read(file) !== content) throw new Error(`Stale/missing HTML output: ${relative(file)}`);
  } else {
    if (fs.existsSync(file) && file.endsWith('.html') && !read(file).startsWith(marker)) throw new Error(`Refusing to overwrite user file: ${relative(file)}`);
    fs.mkdirSync(path.dirname(file), {recursive: true});
    fs.writeFileSync(file, content, 'utf8');
  }
}
// Check outputs without deleting anything the user may have added.
function outputFiles(dir) { return fs.readdirSync(dir, {withFileTypes: true}).flatMap(entry => entry.isDirectory() ? outputFiles(path.join(dir, entry.name)) : [path.join(dir, entry.name)]); }
const stale = outputFiles(output).filter(file => file.endsWith('.html') && read(file).startsWith(marker) && !generated.has(file));
if (stale.length) throw new Error(`Obsolete generated pages need review: ${stale.map(relative).join(', ')}`);
console.log(JSON.stringify({result: 'Pass', mode: check ? 'check' : 'generate', markdownDocuments: files.length, htmlPages: files.length + 1, rewrittenLocalLinks: links.length, output: 'learning/html/index.html'}, null, 2));
