// Optional offline reading copies. No Unreal/runtime dependency.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {Marked, Renderer} from './vendor/marked.mjs';
import {shell as labShell, classify, plain, route, courses} from './html-lab.mjs';

const learning = fileURLToPath(new URL('../', import.meta.url));
const project = path.dirname(learning);
const output = path.join(learning, 'html');
const marker = '<!-- Generated by learning/tools/build-html.mjs. Edit Markdown sources. -->';
const check = process.argv.includes('--check');
if (process.argv.slice(2).some(arg => arg !== '--check')) throw new Error('Usage: node learning/tools/build-html.mjs [--check]');
const walk = dir => fs.readdirSync(dir, {withFileTypes: true}).flatMap(entry => {
  const item = path.join(dir, entry.name);
  if (item === output || entry.name === 'vendor') return [];
  return entry.isDirectory() ? walk(item) : [item];
});
const slash = value => value.replaceAll('\\', '/');
const relative = file => slash(path.relative(learning, file));
const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const digest = value => createHash('sha256').update(value).digest('hex');
const read = file => fs.readFileSync(file, 'utf8');
const inside = file => { const rel = path.relative(project, file); return !rel.startsWith('..') && !path.isAbsolute(rel); };
const files = walk(learning).filter(file => file.endsWith('.md')).sort();
const pages = new Map(files.map(file => [file, path.join(output, relative(file).replace(/\.md$/, '.html'))]));
const expectedPages = new Set([...pages.values(), path.join(output, 'index.html')]);
const url = (from, to) => slash(path.relative(path.dirname(from), to)).split('/').map(encodeURIComponent).join('/');
const css = read(new URL('./html.css', import.meta.url));
const client = read(new URL('./html.js', import.meta.url));
const links = [];
const ids = new Map();
const generated = new Map();
const catalog = [];
const rendered = new Map();

function rewrite(href, source, destination) {
  if (/^(https?:|mailto:)/i.test(href)) return href;
  if (/^[a-z][a-z0-9+.-]*:/i.test(href) || href.startsWith('//')) throw new Error(`Unsupported URL: ${relative(source)} ${href}`);
  const match = /^([^?#]*)(\?[^#]*)?(#.*)?$/.exec(href);
  const target = match[1] ? path.resolve(path.dirname(source), decodeURIComponent(match[1])) : source;
  if (!inside(target) || (!fs.existsSync(target) && !expectedPages.has(target))) throw new Error(`Missing/outside link: ${relative(source)} ${href}`);
  const converted = pages.get(target) || target;
  const fragment = match[3] || '';
  links.push({from: relative(source), target: converted, fragment: decodeURIComponent(fragment.slice(1))});
  return url(destination, converted) + (match[2] || '') + fragment;
}

for (const source of files) {
  const destination = pages.get(source);
  const markdown = read(source);
  const headings = [];
  const usedIds = new Set([...markdown.matchAll(/<a\s+id=["']([^"']+)["']/g)].map(match => match[1]));
  const parser = new Marked({gfm: true, breaks: false});
  const defaults = new Renderer();
  parser.use({renderer: {
    heading(token) {
      const content = this.parser.parseInline(token.tokens);
      const label = content.replace(/<[^>]+>/g, '');
      const base = token.text.toLowerCase().replace(/[^\p{L}\p{N}\s_-]/gu, '').trim().replace(/\s+/g, '-') || 'section';
      let id = base;
      for (let n = 2; usedIds.has(id); n++) id = `${base}-${n}`;
      usedIds.add(id);
      headings.push({id, label, depth: token.depth});
      return `<h${token.depth} id="${escape(id)}">${content}</h${token.depth}>\n`;
    },
    link(token) {
      const href = rewrite(token.href, source, destination);
      return `<a href="${escape(href)}"${token.title ? ` title="${escape(token.title)}"` : ''}>${this.parser.parseInline(token.tokens)}</a>`;
    },
    image(token) {
      return `<img src="${escape(rewrite(token.href, source, destination))}" alt="${escape(token.text)}" loading="lazy">`;
    },
    table(token) {
      return `<div class="table-scroll" role="region" aria-label="가로로 스크롤 가능한 표" tabindex="0">${defaults.table.call(this, token)}</div>`;
    },
    html({text}) {
      // Preserve explicit anchors/line breaks, but never execute document HTML.
      return /^(?:<a\s+id=["'][^"'<>]+["']\s*>(?:\s*<\/a>)?|<\/a>|<br\s*\/?>)\s*$/i.test(text) ? text : escape(text);
    },
  }});
  const body = parser.parse(markdown);
  const title = headings.find(heading => heading.depth === 1)?.label || path.basename(source, '.md');
  const toc = headings.filter(heading => heading.depth > 1 && heading.depth < 4)
    .map(heading => `<a class="level-${heading.depth}" href="#${escape(heading.id)}">${heading.label}</a>`).join('');
  ids.set(destination, usedIds);
  rendered.set(source, {body, toc, headings});
  // Git may normalize CRLF on checkout; hash canonical Markdown text, not host-specific line endings.
  catalog.push({source: relative(source), output: relative(destination), title: plain(title), shortTitle: plain(title).split(' — ')[0], ...classify(relative(source)), sha256: digest(markdown.replace(/\r\n?/g, '\n'))});
}

const index = path.join(output, 'index.html');
const byOutput = new Map([...pages].map(([source, destination]) => [destination, relative(source)]));
const appDocuments = catalog.map(doc => {
  const source = path.join(learning, doc.source);
  const destination = pages.get(source);
  const {body, headings} = rendered.get(source);
  const appBody = body.replace(/(href|src)="([^"]*)"/g, (whole, attr, encoded) => {
    const href = encoded.replaceAll('&amp;', '&');
    if (/^(https?:|mailto:)/i.test(href)) return whole;
    const match = /^([^?#]*)(\?[^#]*)?(#.*)?$/.exec(href);
    const target = match[1] ? path.resolve(path.dirname(destination), decodeURIComponent(match[1])) : destination;
    const anchor = match[3] ? decodeURIComponent(match[3].slice(1)) : '';
    const rewritten = byOutput.has(target) ? route(byOutput.get(target), anchor) : target === index ? '#view=home' : url(index, target) + (match[2] || '') + (match[3] || '');
    return `${attr}="${escape(rewritten)}"`;
  });
  const goal = /<h2[^>]*>[^<]*(?:이번에|목표)[^<]*<\/h2>\s*<p>([\s\S]*?)<\/p>/.exec(appBody);
  return {...doc, body: appBody, headings, text: plain(appBody), goal: goal ? plain(goal[1]) : '', original: url(index, source), standalone: url(index, destination)};
});
for (const doc of catalog) {
  const source = path.join(learning, doc.source);
  const destination = pages.get(source);
  const {body, toc} = rendered.get(source);
  generated.set(destination, labShell({title:doc.title, marker, css, client, catalog, home:url(destination,index), source:doc.source, body, toc, original:url(destination,source)}));
}
generated.set(index, labShell({title:'학습 대시보드', marker, css, client, catalog, data:{documents:appDocuments, courses}}));

for (const link of links) {
  if (link.fragment && ids.has(link.target) && !ids.get(link.target).has(link.fragment)) {
    throw new Error(`Missing HTML anchor: ${link.from} -> ${link.target}#${link.fragment}`);
  }
}
generated.set(path.join(output, 'manifest.json'), JSON.stringify({generator: 'learning/tools/build-html.mjs', parser: 'marked 17.0.5 (MIT)', sourceHashFormat: 'UTF-8 Markdown normalized to LF line endings', documents: catalog}, null, 2) + '\n');
for (const [file, content] of generated) {
  if (check) {
    if (!fs.existsSync(file) || read(file) !== content) throw new Error(`Stale/missing HTML output: ${relative(file)}`);
  } else {
    if (fs.existsSync(file) && file.endsWith('.html') && !read(file).startsWith(marker)) throw new Error(`Refusing to overwrite user file: ${relative(file)}`);
    fs.mkdirSync(path.dirname(file), {recursive: true});
    fs.writeFileSync(file, content, 'utf8');
  }
}
// Check outputs without deleting anything the user may have added.
function outputFiles(dir) { return fs.readdirSync(dir, {withFileTypes: true}).flatMap(entry => entry.isDirectory() ? outputFiles(path.join(dir, entry.name)) : [path.join(dir, entry.name)]); }
const stale = outputFiles(output).filter(file => file.endsWith('.html') && read(file).startsWith(marker) && !generated.has(file));
if (stale.length) throw new Error(`Obsolete generated pages need review: ${stale.map(relative).join(', ')}`);
console.log(JSON.stringify({result: 'Pass', mode: check ? 'check' : 'generate', markdownDocuments: files.length, htmlPages: files.length + 1, rewrittenLocalLinks: links.length, output: 'learning/html/index.html'}, null, 2));
